// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonMicroservice.Entities;

namespace PersonMicroservice.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoardPerson", b =>
                {
                    b.Property<Guid>("BoardsBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembersPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BoardsBoardId", "MembersPersonId");

                    b.HasIndex("MembersPersonId");

                    b.ToTable("BoardPerson");
                });

            modelBuilder.Entity("PersonMicroservice.Entities.Board", b =>
                {
                    b.Property<Guid>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PresidentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BoardId");

                    b.HasIndex("PresidentId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            BoardId = new Guid("8010f254-e872-49d9-9c2c-1d5783719019"),
                            PresidentId = new Guid("2d8607c5-f3cf-4ef5-9323-a9318eee6232")
                        },
                        new
                        {
                            BoardId = new Guid("e53171cc-91f1-4716-8ea8-39b31a97dd84"),
                            PresidentId = new Guid("2d8607c5-f3cf-4ef5-9323-a9318eee6232")
                        });
                });

            modelBuilder.Entity("PersonMicroservice.Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("2d8607c5-f3cf-4ef5-9323-a9318eee6232"),
                            Function = "President",
                            Name = "Davor",
                            Surname = "Jelic"
                        },
                        new
                        {
                            PersonId = new Guid("2411cc63-1a91-4bb2-9432-c2f0515cef63"),
                            Function = "Judge",
                            Name = "Milan",
                            Surname = "Novcic"
                        },
                        new
                        {
                            PersonId = new Guid("81f63012-16d7-4f1a-a330-55dc295a6dcd"),
                            Function = "Member",
                            Name = "Mihajlo",
                            Surname = "Strajin"
                        });
                });

            modelBuilder.Entity("BoardPerson", b =>
                {
                    b.HasOne("PersonMicroservice.Entities.Board", null)
                        .WithMany()
                        .HasForeignKey("BoardsBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonMicroservice.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("MembersPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonMicroservice.Entities.Board", b =>
                {
                    b.HasOne("PersonMicroservice.Entities.Person", "President")
                        .WithMany()
                        .HasForeignKey("PresidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("President");
                });
#pragma warning restore 612, 618
        }
    }
}
