// <auto-generated />
using System;
using AddressMicroservice.Entities.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressMicroservice.Migrations
{
    [DbContext(typeof(AddressContext))]
    [Migration("20220223012141_initionalCrate")]
    partial class initionalCrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressMicroservice.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("StateID");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("07af89f2-feee-4680-b489-9d0e31699588"),
                            Place = "Zagreb",
                            StateID = new Guid("93a08cc2-1d17-46e6-bd95-4fa70bb11226"),
                            Street = "Jadranska avenija",
                            StreetNumber = "23b",
                            ZipCode = "10000"
                        },
                        new
                        {
                            AddressId = new Guid("3a3e6366-3a20-4d3b-ae15-be85ba277683"),
                            Place = "Pancevo",
                            StateID = new Guid("458adb42-62a5-4117-8101-7d933fa88abb"),
                            Street = "Svetog Save",
                            StreetNumber = "5",
                            ZipCode = "26000"
                        },
                        new
                        {
                            AddressId = new Guid("0ec20a3b-fd39-4c2e-8062-7d1664eb5381"),
                            Place = "Skoplje",
                            StateID = new Guid("84ff030b-7067-45b7-8bb2-10719534f91e"),
                            Street = "Drezdenska",
                            StreetNumber = "10",
                            ZipCode = "1010"
                        });
                });

            modelBuilder.Entity("AddressMicroservice.Entities.State", b =>
                {
                    b.Property<Guid>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            StateID = new Guid("93a08cc2-1d17-46e6-bd95-4fa70bb11226"),
                            NameState = "Hrvatska"
                        },
                        new
                        {
                            StateID = new Guid("458adb42-62a5-4117-8101-7d933fa88abb"),
                            NameState = "Srbija"
                        },
                        new
                        {
                            StateID = new Guid("84ff030b-7067-45b7-8bb2-10719534f91e"),
                            NameState = "Makedonija"
                        });
                });

            modelBuilder.Entity("AddressMicroservice.Entities.Address", b =>
                {
                    b.HasOne("AddressMicroservice.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
