// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlotMicroservice.Entities;

namespace PlotMicroservice.Migrations
{
    [DbContext(typeof(PlotContext))]
    [Migration("20220131145137_PlotPartProtectedZoneCreate")]
    partial class PlotPartProtectedZoneCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlotMicroservice.Entities.PlotCadastralMunicipality", b =>
                {
                    b.Property<Guid>("PlotCadastralMunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CadastralMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotCadastralMunicipalityId");

                    b.ToTable("PlotCadastralMunicipalities");

                    b.HasData(
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("93a08cc2-1d17-46e6-bd95-4fa70bb11226"),
                            CadastralMunicipality = "Čantavir"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("458adb42-62a5-4117-8101-7d933fa88abb"),
                            CadastralMunicipality = "Bački Vinogradi"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("84ff030b-7067-45b7-8bb2-10719534f91e"),
                            CadastralMunicipality = "Bikovo"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("98b39864-1763-49d4-91c7-3d95060ebd5e"),
                            CadastralMunicipality = "Đuđin"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("f305096b-52fd-4c43-8699-05bc3ee664b7"),
                            CadastralMunicipality = "Žedin"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("37841f52-2e51-45ea-af4e-bc67b5c5d0e9"),
                            CadastralMunicipality = "Tavankut"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("372d9458-a560-4b56-8119-ada1f7feb723"),
                            CadastralMunicipality = "Bajmok"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("321e3608-d760-4067-bfb5-695784bd2dd3"),
                            CadastralMunicipality = "Donji Grad"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("aee6dace-3f2d-43b5-b853-7d08e20ac81f"),
                            CadastralMunicipality = "Stari Grad"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("5bffadaf-117e-4d87-9f32-ef39e83d1499"),
                            CadastralMunicipality = "Novi Grad"
                        },
                        new
                        {
                            PlotCadastralMunicipalityId = new Guid("0c0e2227-531a-4f0d-83f0-a1d4a52f4676"),
                            CadastralMunicipality = "Palić"
                        });
                });

            modelBuilder.Entity("PlotMicroservice.Entities.PlotCulture", b =>
                {
                    b.Property<Guid>("PlotCultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotCultureId");

                    b.ToTable("PlotCultures");

                    b.HasData(
                        new
                        {
                            PlotCultureId = new Guid("ba9777ce-d43f-4f71-a163-7c974e36654f"),
                            Culture = "Njive"
                        },
                        new
                        {
                            PlotCultureId = new Guid("60644cdd-795b-47a2-96ac-55f623862efe"),
                            Culture = "Vrtovi"
                        },
                        new
                        {
                            PlotCultureId = new Guid("2484a534-4e5f-4b0c-af35-190ae0d68fcc"),
                            Culture = "Voćnjaci"
                        },
                        new
                        {
                            PlotCultureId = new Guid("7b199139-6b41-4087-89b0-84d911b5fe2b"),
                            Culture = "Vinogradi"
                        },
                        new
                        {
                            PlotCultureId = new Guid("97adad6e-f225-4164-8830-b59004c812c3"),
                            Culture = "Livade"
                        },
                        new
                        {
                            PlotCultureId = new Guid("cc506ecd-fb9e-48d8-af90-26ecc5d9feba"),
                            Culture = "Pašnjaci"
                        },
                        new
                        {
                            PlotCultureId = new Guid("3262a3e8-a113-431f-8f2f-98a10d97c5a4"),
                            Culture = "Šume"
                        },
                        new
                        {
                            PlotCultureId = new Guid("a0c1727d-bb2c-4243-a907-be6f3a005558"),
                            Culture = "Trstici-močvare"
                        });
                });

            modelBuilder.Entity("PlotMicroservice.Entities.PlotPartClass", b =>
                {
                    b.Property<Guid>("PlotPartClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotPartClassId");

                    b.ToTable("PlotPartClasses");

                    b.HasData(
                        new
                        {
                            PlotPartClassId = new Guid("1794fc01-2d12-4f5d-aaec-7eb219635052"),
                            Class = "I"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("5b957c06-8ca6-4658-ad45-78e62c465b3d"),
                            Class = "II"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("6f2629db-8de7-496c-97e0-75b1a94b1db3"),
                            Class = "III"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("5e69aeb5-4fec-4dd9-ba69-a474f06721f2"),
                            Class = "IV"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("3a3e6366-3a20-4d3b-ae15-be85ba277683"),
                            Class = "V"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("b2ddef8e-eddc-4fb0-884b-1701ab983bed"),
                            Class = "VI"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("a9a4427b-889d-4be4-bf9c-386edb323d9c"),
                            Class = "VII"
                        },
                        new
                        {
                            PlotPartClassId = new Guid("1965dce3-a24a-4e7c-a6d1-fddbbfeabc44"),
                            Class = "VIII"
                        });
                });

            modelBuilder.Entity("PlotMicroservice.Entities.PlotPartFormOfOwnership", b =>
                {
                    b.Property<Guid>("PlotPartFormOfOwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormOfOwnership")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotPartFormOfOwnershipId");

                    b.ToTable("PlotPartFormOfOwnerships");

                    b.HasData(
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("06d92fec-8bd5-4be1-a772-f52ae7ff6ee3"),
                            FormOfOwnership = "Privatna svojina"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("f5f92ac7-0682-48a6-bd34-f2f5d89be9a0"),
                            FormOfOwnership = "Državna svojina RS"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("3075f4ce-e8f4-4b68-bd22-246363d71a57"),
                            FormOfOwnership = "Državna svojina"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("aa444022-1e63-44f5-8cf4-7df5045af184"),
                            FormOfOwnership = "Društvena svojina"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("b8e349da-6c4d-4282-acb1-872628128fc1"),
                            FormOfOwnership = "Zadružna svojina"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("07af89f2-feee-4680-b489-9d0e31699588"),
                            FormOfOwnership = "Mešovita svojina"
                        },
                        new
                        {
                            PlotPartFormOfOwnershipId = new Guid("a2c789e8-9e35-43d6-bf2e-156d776aeceb"),
                            FormOfOwnership = "Drugi oblici"
                        });
                });

            modelBuilder.Entity("PlotMicroservice.Entities.PlotPartProtectedZone", b =>
                {
                    b.Property<Guid>("PlotPartProtectedZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProtectedZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotPartProtectedZoneId");

                    b.ToTable("PlotPartProtectedZones");

                    b.HasData(
                        new
                        {
                            PlotPartProtectedZoneId = new Guid("f66b8360-33d2-48e9-9be5-b208988d1fb1"),
                            ProtectedZone = "1"
                        },
                        new
                        {
                            PlotPartProtectedZoneId = new Guid("e54364be-1fe6-43b5-9401-8b8bd2165aba"),
                            ProtectedZone = "2"
                        },
                        new
                        {
                            PlotPartProtectedZoneId = new Guid("de569d06-4787-4808-b4f6-0efea24f6b03"),
                            ProtectedZone = "3"
                        },
                        new
                        {
                            PlotPartProtectedZoneId = new Guid("4debaa6a-1a2f-43e0-bb82-1b7ca1824318"),
                            ProtectedZone = "4"
                        });
                });

            modelBuilder.Entity("PlotMicroservice.Entities.PlotWorkability", b =>
                {
                    b.Property<Guid>("PlotWorkabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Workability")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotWorkabilityId");

                    b.ToTable("PlotWorkabilities");

                    b.HasData(
                        new
                        {
                            PlotWorkabilityId = new Guid("c0615a4d-faa4-4e17-8f2f-93ec25383f9b"),
                            Workability = "Obradivo"
                        },
                        new
                        {
                            PlotWorkabilityId = new Guid("40d2641b-8b85-4625-b01c-a129389a6aad"),
                            Workability = "Ostalo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
