// <auto-generated />
using System;
using DocumentMicroservice.Entities.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentMicroservice.Migrations
{
    [DbContext(typeof(DocumentContext))]
    partial class DocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentMicroservice.Entities.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DocumentCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocStatusID");

                    b.ToTable("Document");

                    b.HasData(
                        new
                        {
                            DocumentId = new Guid("07af89f2-feee-4680-b489-9d0e31699588"),
                            DocStatusID = new Guid("93a08cc2-1d17-46e6-bd95-4fa70bb11226"),
                            DocumentCreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentTemplate = "Kreiranje predloga plana",
                            RegistrationNumber = "119833332"
                        },
                        new
                        {
                            DocumentId = new Guid("3a3e6366-3a20-4d3b-ae15-be85ba277683"),
                            DocStatusID = new Guid("458adb42-62a5-4117-8101-7d933fa88abb"),
                            DocumentCreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentTemplate = "Obrazovanje komisije za davanje misljenja",
                            RegistrationNumber = "122267432"
                        },
                        new
                        {
                            DocumentId = new Guid("0ec20a3b-fd39-4c2e-8062-7d1664eb5381"),
                            DocStatusID = new Guid("84ff030b-7067-45b7-8bb2-10719534f91e"),
                            DocumentCreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentTemplate = "Saglasnost ministra",
                            RegistrationNumber = "119834232"
                        });
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.DocumentStatus", b =>
                {
                    b.Property<Guid>("DocStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocStatusID");

                    b.ToTable("DocumentStatus");

                    b.HasData(
                        new
                        {
                            DocStatusID = new Guid("93a08cc2-1d17-46e6-bd95-4fa70bb11226"),
                            Status = "Usvojen"
                        },
                        new
                        {
                            DocStatusID = new Guid("458adb42-62a5-4117-8101-7d933fa88abb"),
                            Status = "Odbijen"
                        },
                        new
                        {
                            DocStatusID = new Guid("84ff030b-7067-45b7-8bb2-10719534f91e"),
                            Status = "Otvoren"
                        });
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.GuaranteeType", b =>
                {
                    b.Property<Guid>("GuaranteeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuaranteeTypeID");

                    b.ToTable("GuaranteeTypes");

                    b.HasData(
                        new
                        {
                            GuaranteeTypeID = new Guid("f5f92ac7-0682-48a6-bd34-f2f5d89be9a0"),
                            Type = "Jemstvo"
                        },
                        new
                        {
                            GuaranteeTypeID = new Guid("ce8229bf-0853-4ae9-b0ed-59c9e5607d64"),
                            Type = "Bankarska garancija"
                        },
                        new
                        {
                            GuaranteeTypeID = new Guid("372d9458-a560-4b56-8119-ada1f7feb723"),
                            Type = "Garancija nekretnine"
                        },
                        new
                        {
                            GuaranteeTypeID = new Guid("e54364be-1fe6-43b5-9401-8b8bd2165aba"),
                            Type = "Zirantska"
                        },
                        new
                        {
                            GuaranteeTypeID = new Guid("68bf5d70-f26b-4c53-b014-bab74b7b86a0"),
                            Type = "Uplata gotovine"
                        });
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.Document", b =>
                {
                    b.HasOne("DocumentMicroservice.Entities.DocumentStatus", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
